### ISSUE TITLE
Chaincode: Get installed package

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-admin-sdk#102]
**As a** user of the admin SDK
**I want** to get an installed chaincode package from a peer
**So that** I have an API equivalent to the `peer lifecycle chaincode getinstalledpackage` CLI command

**Comment by SamYuan1990** [comment]
@bestbeforetoday , do you mean we can have a cli folder and impl some CLI binary files?

**Comment by SamYuan1990** [comment]
or we just provide API feature?

**Comment by bestbeforetoday** [comment]
Just an API call to provide the capability. Later a CLI could be implemented using that API, but the intent here is just to provide the API call, not a CLI.
