### ISSUE TITLE
to suppport channel.GetConfigBlockFromOrderer(...)

### ISSUE THREAD

**Issue by 1gezhanghao** [hyperledger/fabric-admin-sdk#104]
As a user of the admin SDK
I want to inspect blockconfig from orderer node (not from peer)
So that I can get the blcokconfig from a orderer cluster when it has no peer.

**Comment by SamYuan1990** [comment]
May I know if this duplicate with #105 for now?
if so, @1gezhanghao , please close as duplicate.

**Comment by SamYuan1990** [comment]
@1gezhanghao , I am going to close this issue, as it seems duplicate with #105 , please reopen if any further needed.
