### ISSUE TITLE
Try to enable go lint with options

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-admin-sdk#117]
```
#- varcheck
  #- gocyclo
  #- bodyclose
  #- misspell
  #- nakedret
  #- unconvert
  # - goconst
  # - gocritic
  # - noctx
  # - whitespace
  # - dupl
```
to improve our code quantity with lint options above.

**Comment by SamYuan1990** [comment]
@channingduan , could you please take a look at this issue?

**Comment by bestbeforetoday** [comment]
Just for reference, the current set of linters being run (in addition to staticcheck) are:

- errcheck
- gofmt
- goimports
- gosec
- gosimple
- govet
- ineffassign
- typecheck
- unused

The active linters are configured in [.golangci.yml](https://github.com/hyperledger/fabric-admin-sdk/blob/main/.golangci.yml). See the [golangci-lint documentation](https://golangci-lint.run/usage/linters/) for available linters.

**Comment by SamYuan1990** [comment]
> Just for reference, the current set of linters being run (in addition to staticcheck) are:
> 
> * errcheck
> * gofmt
> * goimports
> * gosec
> * gosimple
> * govet
> * ineffassign
> * typecheck
> * unused
> 
> The active linters are configured in [.golangci.yml](https://github.com/hyperledger/fabric-admin-sdk/blob/main/.golangci.yml). See the [golangci-lint documentation](https://golangci-lint.run/usage/linters/) for available linters.

thanks a lot for comments, updated scope.
