### ISSUE TITLE
to support list channels peer has joined

### ISSUE THREAD

**Issue by 1gezhanghao** [hyperledger/fabric-admin-sdk#123]
As a user of the admin SDK
I want to list channels that a peer joined
So that I can know which channels the peer node has joined.

peer cli command is as follows
```
List of channels peer has joined.

Usage:
  peer channel list [flags]

Flags:
  -h, --help   help for list

Global Flags:
      --cafile string                       Path to file containing PEM-encoded trusted certificate(s) for the ordering endpoint
      --certfile string                     Path to file containing PEM-encoded X509 public key to use for mutual TLS communication with the orderer endpoint
      --clientauth                          Use mutual TLS when communicating with the orderer endpoint
      --connTimeout duration                Timeout for client to connect (default 3s)
      --keyfile string                      Path to file containing PEM-encoded private key to use for mutual TLS communication with the orderer endpoint
  -o, --orderer string                      Ordering service endpoint
      --ordererTLSHostnameOverride string   The hostname override to use when validating the TLS connection to the orderer
      --tls                                 Use TLS when communicating with the orderer endpoint
      --tlsHandshakeTimeShift duration      The amount of time to shift backwards for certificate expiration checks during TLS handshakes with the orderer endpoint
```

**Comment by SamYuan1990** [comment]
@denyeart , what do you think? can we start use admin-sdk to generate some binary and which able to replace peer cli or decouple peer cli from peer node binary?

**Comment by 1gezhanghao** [comment]
@SamYuan1990  yes, just API is good enough.

**Comment by denyeart** [comment]
Yes, I think a CLI based on admin SDK is the logical conclusion. Let's first get the API fairly complete though.
Note that https://github.com/hyperledger/fabric-cli was started but never completed... it could be picked back up as the eventual CLI.

**Comment by SamYuan1990** [comment]
> Yes, I think a CLI based on admin SDK is the logical conclusion. Let's first get the API fairly complete though. Note that https://github.com/hyperledger/fabric-cli was started but never completed... it could be picked back up as the eventual CLI.

Ok, we can make admin-sdk focus on logical and API,  and fabric-cli can relay on admin-sdk for features.

**Comment by SamYuan1990** [comment]
> @SamYuan1990 yes, just API is good enough.

https://github.com/hyperledger/fabric-admin-sdk/blob/main/pkg/channel/channel.go#L63 does this work?

**Comment by 1gezhanghao** [comment]
no，OSN can list orderer node‘s channel ，not for peer.

**Comment by SamYuan1990** [comment]
> no，OSN can list orderer node‘s joined channel ，not for peer.

k.... as your sample is from orderer. I got it.
```
List of channels peer has joined.

Usage:
  peer channel list [flags]

Flags:
  -h, --help   help for list

Global Flags:
      --cafile string                       Path to file containing PEM-encoded trusted certificate(s) for the ordering endpoint
      --certfile string                     Path to file containing PEM-encoded X509 public key to use for mutual TLS communication with the orderer endpoint
      --clientauth                          Use mutual TLS when communicating with the orderer endpoint
      --connTimeout duration                Timeout for client to connect (default 3s)
      --keyfile string                      Path to file containing PEM-encoded private key to use for mutual TLS communication with the orderer endpoint
  -o, --orderer string                      Ordering service endpoint
      --ordererTLSHostnameOverride string   The hostname override to use when validating the TLS connection to the orderer
      --tls                                 Use TLS when communicating with the orderer endpoint
      --tlsHandshakeTimeShift duration      The amount of time to shift backwards for certificate expiration checks during TLS handshakes with the orderer endpoint
```

**Comment by 1gezhanghao** [comment]
yes, the peer cmd had supported to find channels it joined.
and i need this api in fabric-admin-sdk

**Comment by SamYuan1990** [comment]
> yes, the peer cmd has always supported to find channels it joined. that is `peer channel list --help` info , it may help you to trace the implements code. and i need this API in fabric-admin-sdk

I will take a look at, as orderer and peer are different interface at implementation level.
