### ISSUE TITLE
golang features implementation

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-admin-sdk#15]
# Channel
- [x] #18
- [x] #30
- [x] #19
- [x] #31
- [x] #42 

# Chaincode
- [x] #23
- [x] chaincode package java
- [x] #94
- [x] chaincode package nodejs
- [x] #25
- [x] #49
- [x] #102
- [x] #37
- [x] #28
- [x] #35
- [x] #36
- [x] #29
- [x] #39

# tools
- [x] #16
- [ ] gate policy
- [ ] peer discovery
- [x] generate connection profile for sdk

**Comment by SamYuan1990** [comment]
@jkneubuh FYI

**Comment by jkneubuh** [comment]
Thanks @SamYuan1990 those look like a good set of features for addition to the library.   A couple of questions / comments: 

- `peer channel unjoin` might not be possible with the current implementation in Fabric.  To unjoin a channel, the peer MUST be shut down or set into maintenance mode.   If the admin SDK does not include the ability to stop and restart the peer, this feature will not work correctly.    (This seems like a feature enhancement for Fabric, not for the admin SDK.)

- Does the feature set above allow for the registration of a new Org to a channel?

**Comment by denyeart** [comment]
@SamYuan1990 Have you looked at the fabric-config library?
https://github.com/hyperledger/fabric-config
https://pkg.go.dev/github.com/hyperledger/fabric-config/configtx
It contains a Go API to create and update channel configuration (including adding a new org). When this library was created, the idea was that a new channel config SDK or CLI would use the new API to replace the existing challenging channel config approach (configtxgen, JSON manipulation, etc). However, the people working on this left the project before such a SDK or CLI could be created. It would make a lot of sense for the Go based fabric-admin-sdk to pick up where this effort left off and use the fabric-config API library for the channel operations. What do you think?

**Comment by SamYuan1990** [comment]
@denyeart, @jkneubuh , @davidkhala ,
here is my plan.
I would like to follow TDD method to development this admin sdk project.
if this admin sdk project can be used in decouple peer cli with peer server in further, that's great but not current goal/target.
so far, personally we have 3/4 kinds of implementation plan
-  internal/fabric package
- fabric-config project
- fabric-gateway(as identity related part)
- making fabric as dependency in go mod 

so, 1st of all, I would like to follow TDD method to implement all features.
and as 2nd phase, we may decouple fabric code/dependency from go sdk implementation, which will be 2nd phase implementation. targeting at decouple peer cli from peer server.

because of for operator(labs project) point of view, a sdk project it has fabric dependency there https://github.com/hyperledger-labs/fabric-operator/blob/main/go.mod#L11 and for decouple peer cli and peer server and if we plan to merge back to fabric repo(if needed) then the implementation should be keep.

**Comment by SamYuan1990** [comment]
`peer node unjoin` is removed from scope, as it not admin sdk but running on peer node side.

**Comment by SamYuan1990** [comment]
@jkneubuh , @denyeart , we nearly close to 1st MVP version as major replacement with fabric test-network cli commands. FYI

**Comment by samuelvenzi** [comment]
Hi @SamYuan1990 and @bestbeforetoday, I managed to develop the query committed function (#39) and would like to start contributing to the project. 

It was only possible with the refactor in PR #87 so I'll wait for the approval and merge so I can get the modifications from `main` before opening a PR.

**Comment by bestbeforetoday** [comment]
Channel configuration needs to have the capability to set anchor peers, otherwise service discovery does not work.

**Comment by bestbeforetoday** [comment]
> Hi @SamYuan1990 and @bestbeforetoday, I managed to develop the query committed function (#39) and would like to start contributing to the project.

Contributions would be very welcome! We probably need to have a pass through the work still outstanding and make sure everything is raised as separate issues so we can more easily assign who is actually working on them. I will make a start on that from my perspective as soon as I can.

**Comment by bestbeforetoday** [comment]
@samuelvenzi PR #87 is now merged so you can base changes in top of that.

**Comment by samuelvenzi** [comment]
> @samuelvenzi PR #87 is now merged so you can base changes in top of that.

Thanks, @bestbeforetoday. It's on #88

**Comment by samuelvenzi** [comment]
Hi @SamYuan1990. Is this issue still relevant? If not, what are some pending features that I cook take a look?

**Comment by samuelvenzi** [comment]
@SamYuan1990 any pointers on how I can help? 😄

**Comment by davidkhala** [comment]
> @SamYuan1990 any pointers on how I can help? 😄

I think `peer discovery` feature is what you can work on in priority.

**Comment by SamYuan1990** [comment]
> > @SamYuan1990 any pointers on how I can help? 😄
> 
> I think `peer discovery` feature is what you can work on in priority.

thanks @davidkhala, I just received from sick in recent , @samuelvenzi yes, you can start with peer discovery. :-)

**Comment by davidkhala** [comment]
@SamYuan1990 Considering that most of sdk users have now migrated to peer gateway, I would like to label item `generate connection profile for sdk` as WON'T DO. Open to hear your thoughts.

**Comment by SamYuan1990** [comment]
> @SamYuan1990 Considering that most of sdk users have now migrated to peer gateway, I would like to label item `generate connection profile for sdk` as WON'T DO. Open to hear your thoughts.

LGTM, and I am supposing we are good with this ticket and going to close it.
ask tooling should move to fabric-cli repo fro discussion.
