### ISSUE TITLE
Transfer to Hyperledger labs

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-admin-sdk#40]
### Is your proposal related to a problem?

To avoid duplicate woks, pre discussed with @denyeart and @bestbeforetoday offline, we hope to transform this repo to labs.

### Describe the solution you'd like

create a labs rfc and transform this repo to labs.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by SamYuan1990** [comment]
- [x]  @SamYuan1990 , I am good to transfer golang part to labs.
- [ ] @davidkhala , please confirm for transfer nodejs code to labs.
- [ ] @xiaohui249 , @channingduan for java part, we will implement later, as current java code in this repo is empty.

**Comment by denyeart** [comment]
We've discussed with Fabric SDK lead maintainers and there is support for moving the admin SDK directly to a fabric subproject (e.g. hyperledger/fabric-admin-sdk, or one per language, starting with Go). Then all parties can collaborate in the official subproject and make the admin SDK a first class project in the Fabric ecosystem, similar to the other transactional SDKs. All that would be needed is to open a proposal in https://github.com/hyperledger/fabric-rfcs and get Fabric maintainers and SDK maintainers agreement.

What do the TWGC members think?

**Comment by SamYuan1990** [comment]
pre discussed with @davidkhala at https://wiki.hyperledger.org/display/TWGC/2022-11-09 we are agree moving to hyperledger/fabric-admin-sdk. I will submit an rfc for this later. We can start from golang and js.

**Comment by channingduan** [comment]
:ok_hand: that is good idea.

**Comment by xiaohui249** [comment]
Although the Java code is not ready, but the golang and nodejs code are already. Moving to a fabric subproject is a meaningful thing in the long run. I agree with it.

**Comment by SamYuan1990** [comment]
submit fabric rfc at https://github.com/hyperledger/fabric-rfcs/pull/55

**Comment by SamYuan1990** [comment]
remove stale, as waiting rfc is under review process.

**Comment by SamYuan1990** [comment]
close as completed
