### ISSUE TITLE
golang 1st release

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-admin-sdk#61]
### Is your proposal related to a problem?
n/A

### Describe the solution you'd like
we need 
- go doc as online document #53 
- finish most of features in #15 
- an e2e sample https://github.com/hyperledger/fabric-admin-sdk/blob/main/test/e2e_test.go
- tag release with CI(no need)
- tag as x.y.z for the 1st one, we use 0.0.0-alpha
- a recording sample?(as post release action)

### Describe alternatives you've considered
n/A

### Additional context
n/A

**Comment by SamYuan1990** [comment]
@bestbeforetoday , @davidkhala , @channingduan once we merged with #79 , I will create a release as v0.0.0-alpha. please let me know if you have any other tickets need to be done before v0.0.0-alpha release.

**Comment by SamYuan1990** [comment]
will use #121 as CI for release.

**Comment by davidkhala** [comment]
I see v0.0.0 was released in July 2023.
If any further issues, reopen is welcomed.
