### ISSUE TITLE
BFT support after smart BFT in fabric.

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-admin-sdk#67]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by davidkhala** [comment]
Now it is certain that BFT has been included in Fabric 3.

**Comment by SamYuan1990** [comment]
I suppose we make it here https://github.com/hyperledger/fabric-admin-sdk/blob/main/.github/workflows/golang.yml#L57
